import type { Metadata } from "next";
import "./globals.css";
import { Cinzel } from "next/font/google";

const poppins = Cinzel({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "WebGL Sakura",
  description: "Generated by Vergil1000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased h-screen w-full`}
      >
        {children}
      </body>
    </html>
  );
}
